blog/urls.py
from django.urls import path,re_path
from . import views

app_name = 'blog'
#第一种方法path
urlpatterns = [
    path('index/', views.index),
    path('article/<int:article_id>/', views.article_page,name='article_page'),
    path('edit/<int:article_id>/', views.edit_page,name='edit_page'),
    path('edit_action/', views.edit_action,name='edit_action')
]

#第二种方法re_path
# urlpatterns = [
#     re_path('index/', views.index),
#     re_path('article/(?P<article_id>[0-9]+)/', views.article_page),
# ]

# urlpatterns = [
#     path('index/',views.index),
#     re_path('article/(?P<article_id>[0-9]+)/', views.article_page), #使用正则表达式配置路由
# ]

myblog/urls.py
from django.contrib import admin
from django.urls import path,include

import blog.views as bv
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace='blog')),
]

blog/models.py
from __future__ import unicode_literals

from django.db import models

class Article(models.Model):
    title = models.CharField(max_length=32,default='Title')
    content = models.TextField(null=True)
    pub_time = models.DateTimeField(null=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render  #render 渲染
from django.http import HttpResponse

from . import  models
def index(request):
    #article = models.Article.objects.get(pk=1) 以指定获取数据
    articles = models.Article.objects.all()   # 获取所有数据
    return render(request,'index.html',{'articles':articles})

def article_page(request,article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request,'article_page.html',{'article':article})

def edit_page(request,article_id):
    if str(article_id) == '0':
        return  render(request,'edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'edit_page.html', {'article': article})

def edit_action(request):
    title =request.POST.get('title','TITLE')
    content = request.POST.get('content','CONTENT')
    article_id = request.POST.get('article_id','0')
    if article_id == '0':
        models.Article.objects.create(title=title,content=content)
        articles = models.Article.objects.all()
        return render(request, 'index.html', {'articles': articles})

    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()
    return render(request,'article_page.html',{'article':article})

blog/templates/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
</head>
<body>
   <h3>{{ article.title }}</h3>
    <h3>{{ article.content }}</h3>
<h2><a href="{% url 'blog:edit_page' article.id %}">修改文章</a></h2>
</body>
</html>

blog/templates/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="article_id" value="{{ article.id | default:'0'}}">  #过滤器
    <lable>文章标题
        <input type="text" name="title" value="{{ article.title }}">
    </lable>
     <lable>文章内容
        <input type="text" name="content" value="{{ article.content }}">
    </lable>
    <br>
{#    第二种方法#}
{#    {% if article %}#}
{#        <input type="hidden" name="article_id" value="{{ article.id }}">#}
{#    <lable>文章标题#}
{#        <input type="text" name="title" value="{{ article.title }}">#}
{#    </lable>#}
{#     <lable>文章内容#}
{#        <input type="text" name="content" value="{{ article.content }}">#}
{#    </lable>#}
{#    <br>#}
{#    {% else %}#}
{#        <input type="hidden" name="article_id" value="0">#}
{#    <lable>文章标题#}
{#        <input type="text" name="title">#}
{#    </lable>#}
{#     <lable>文章内容#}
{#        <input type="text" name="content">#}
{#    </lable>#}
{#    <br>#}
{#    {% endif %}#}
    <input type="submit" value="提交">
</form>
</body>
</html>

blog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1><a href="{% url 'blog:edit_page' 0 %}">新文章</a></h1>
{% for article in articles %}
   <h2><a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a></h2>
{% endfor %}
</body>
</html>